image: docker:19.03.1
services:
  - docker:19.03.1-dind

stages:
  - test
  - cleanup

test:
  stage: test
  script:
    - echo "Testing pull selenium/standalone-chrome"
    - docker pull selenium/standalone-chrome:latest
    - echo "Testing run selenium/standalone-chrome"
    - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:latest
    - echo "Testing pull maven"
    - docker pull maven
    - docker build maven
    - docker run mvn clean install
    - mvn clean test
  only:
    - pushes

cleanup:
  stage: cleanup
  when: always
  script:
    - echo "Stop & remove containers"
    - docker rm $(docker ps -a -q)