image: selenium/standalone-chrome

test1:
  script:
    - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-xenon
test2:
  script:
    - mvn clean test
  only:
    - pushes