image: docker:git

services:
  - docker:dind

test:
  script:
    - docker pull selenium/standalone-chrome:latest
    - docker pull maven:3.6.2-jdk-8
    - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:latest
    - docker run --tty --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven mvn clean install
  only:
    - pushes