image: maven
services:
  - maven:dind

stages:
  - test

test:
  stage: test
  script:
    - echo "Testing pull selenium/standalone-chrome"
    - docker pull selenium/standalone-chrome:latest
    - echo "Testing run selenium/standalone-chrome"
    - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:latest
    - mvn clean test
  only:
    - pushes